# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.101
    - name: Display dotnet version
      run: dotnet --version
    - name: Test
      run: |
        cd TestProject1
        dotnet run
    - name: Publish
      run: |
        cd TestProject1
        dotnet publish --configuration Release -bl
    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: "**/*.binlog"
    - name: Run published
      run: |
        cd TestProject1/bin/Release/net*/publish
        dotnet TestProject1.dll
      continue-on-error: true
